### ISSUE TITLE
Train不成啊 有bug

### ISSUE THREAD

**Issue by raywzy** [wllvcxz/faster-rcnn-pytorch#1]
QwQ 麻烦看一下utils/loss.py  loss = loss / (anchor_label.data >=0).sum()  显示变量类型不对 应该是cuda.Float的

**Comment by ghost** [comment]
Same here:
Traceback (most recent call last):
  File "trainer.py", line 44, in <module>
    loss = model.loss(img, bbox, label)
    /loss.py", line 49, in delta_loss
    loss = loss / (anchor_label.data >=0).sum()
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.cuda.LongTensor for argument #2 'other'

**Comment by yurynamgung** [comment]
Try this instead  

  loss = torch.div(loss, (anchor_label.data >=0).sum().type(torch.FloatTensor))

you may need to do type(torch.cuda.FloatTensor)

however, when I made this change, I got that loss had a size of 0
this issue existed before I made this suggested change

**Comment by wllqwzx** [comment]
Bug fixed.
